#%RAML 0.8
---
title: VPDB API
baseUri: https://vpdb.ch/api/v1
protocols: [HTTPS]
mediaType: application/json

schemas:
  - comment: !include _schemas/comment.json
  - game: !include _schemas/game.json
  - release: !include _schemas/release.json
  - tag: !include _schemas/tag.json
  - build: !include _schemas/build.json
  - auth: !include _schemas/auth.json
  - user: !include _schemas/user.json
  - user-authenticate: !include _schemas/user-authenticate.json
  - user-chpass: !include _schemas/user-chpass.json
  - user-create-local: !include _schemas/user-create-local.json
  - user-register: !include _schemas/user-register.json
  - user-update-profile: !include _schemas/user-update-profile.json
  - user-token-confirmation: !include _schemas/user-token-confirmation.json

securitySchemes:
  - jwt: !include _securitySchemes/jwt.raml

traits:
  - protected: !include _traits/protected.raml
  - validated: !include _traits/validated.raml
  - paginated: !include _traits/paginated.raml

/games: !include games/games.raml
/releases: !include releases/releases.raml
/tags: !include tags/tags.raml
/builds: !include builds/builds.raml
/roms: !include roms/roms.raml
/users: !include users/users.raml
/user: !include user/user.raml
/authenticate: !include auth/auth.raml
