displayName: Files
description: |
  The storage API for uploading and downloading individual files. Contrarily to
  the API's [files resource][core-files], this deals with the *file content*, while the
  core API deals with the file's *meta data*.

  [core-files]: api://core/files

post:
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    Upload a new file.

    Data can be either sent as the entire body or as multipart request. In
    either case, `Content-Type` must be set.

    However, due to a `XMLHttpRequest` limitation, content types of individual
    parts cannot be set through a browser, so when posting multipart data, the
    content type must be provided through a `content_type` query parameter.

    Only one file is allowed per multipart request. Fields are ignored.

/{storage_id}:
  get:
    is: [ rateLimited ]
    description: |
      Download an existing file.
  uriParameters:
      storage_id:
        displayName: Storage ID
        type: string

  /{variation_name}:
    get:
      description: |
        Download a variation of an existing file.
    uriParameters:
        variation_name:
          displayName: Variation name
          type: string
