displayName: Tags
description: |
  Tags are a simple way to mark special features of a given [release][release].

  Their purpose is advertising such features to the user and to filter releases
  based on selected tags.

  [release]: api://core/releases

post:
  is: [ validated ]
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    Create a new tag.

  body:
    role/member:
      schema: tag
      example: !include http/create-req.json
  responses:
    201:
      body:
        role/member:
          schema: tag
          example: !include http/create-res-201.json
    422:
      body:
        role/member:
          example: !include http/create-res-422.json

get:
  securedBy: [ ]
  description: |
    List all tags.

    Note that this resource isn't paginated, there should only a few dozen
    of tags for some time.
  body:
    role/anon:
      example: !include http/list-req.json
  responses:
    200:
      body:
        role/anon:
          example: !include http/list-res-200.json


/{tag_id}:
  delete:
    is: [ protected ]
    securedBy: [ jwt: { scopes: [ MEMBER, CONTRIB ] } ]
    description: |
      Delete a tag of a given ID.

      Members can only delete own tags, while contributors can delete any tag.
    responses:
      401:
        body:
          role/anon:
            example: !include http/del-res-401.json
      403:
        body:
          role/member:
            example: !include http/del-res-403.json