#%RAML 0.8
---
title: VPDB API
baseUri: https://vpdb.ch/api
protocols: [HTTPS]
mediaType: application/json

schemas:
  - user: !include _schemas/user.json
  - user-register: !include _schemas/user-register.json

securitySchemes:
  - jwt: !include _securitySchemes/jwt.raml

traits:
  - protected: !include _traits/protected.raml
  - validated: !include _traits/validated.raml

/users: !include users/users.raml