#%RAML 0.8
---
title: VPDB API
baseUri: https://vpdb.ch/api
protocols: [HTTPS]
mediaType: application/json

securitySchemes:
  - jwt: !include _securitySchemes/jwt.raml

traits:
  - root-protected: !include _traits/root-protected.raml

/users: !include users/index.raml