post:
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  is: [ validated ]
  description: |
    Rate a game.

    Note that this can only be done once per game, for rating changes
    use `PUT`.
  body:
    role/member:
      example: !include http/create-rating-req.json
  responses:
    200:
      body:
        role/member:
          example: !include http/create-rating-res-201.json
    422:
      description: Validation errors
      body:
        role/member:
          example: !include http/create-rating-res-422.json
    400:
      description: Wrong HTTP verb
      body:
        role/member:
          example: !include http/create-rating-res-400.json