#%RAML 0.8
---
title: VPDB API
baseUri: https://storage.vpdb.io/v1
protocols: [HTTPS]
mediaType: application/json

securitySchemes:
  - jwt: !include _securitySchemes/jwt.raml

traits:
  - protected: !include _traits/protected.raml
  - rateLimited: !include _traits/rate-limited.raml

/files: !include files/files.raml
/authenticate: !include auth/auth.raml
