queryParameters:
  moderation:
    description: |
      Returns entities that are other than approved.

      You must be logged as moderator, otherwise a `403` is returned.

      One of the following:

        - `pending` - List entities that are not approved or refused yet
        - `refused` - List refused entities
        - `manually_approved` - List entities that were manually approved
        - `auto_approved` - List entities that were auto-approved
        - `all` - List all entities
    required: false
    type: string
    example: pending
