queryParameters:
  page:
    description: Current page to return.
    required: false
    type: integer
  per_page:
    description: |
      How many items per page to return.

      * Default: `<<defaultPerPage>>`
      * Maximal number: `<<maxPerPage>>`
    required: false
    type: integer