#!/bin/sh

################ config start ################

KEEP_DEPLOYMENTS=5
DEPLOY_ROOT=/var/www

################  config end  ################

abort() {
	echo
	echo "  $@" 1>&2
	echo
	exit 1
}

npm_install() {
	echo Installing Node.js dependencies...
	cd ${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	npm install
	test $? -eq 0 || abort Failed to run npm install.
}

repo_clone() {
	local dest=${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	if [ -d "$dest" ]; then
		abort $1 is already deployed, aborting.
	fi
	git clone $PWD ${dest}
    test $? -eq 0 || abort Failed to clone into ${dest}
}

repo_link() {
	echo Swapping code...
	local dest=${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	ln -sfn ${dest} ${DEPLOY_ROOT}/${DEPLOY_ENV}/current
	test $? -eq 0 || abort Failed to symlink current repo.
}

repo_cleanup() {
	local regex=$1
	local dir=${DEPLOY_ROOT}/${DEPLOY_ENV}
	echo Deleting old deployments:
	(ls -t ${dir}|egrep ${regex}|head -n ${KEEP_DEPLOYMENTS};ls ${dir}|egrep ${regex})|sort|uniq -u|xargs -I {} echo "   * ${dir}/{}"
	(ls -t ${dir}|egrep ${regex}|head -n ${KEEP_DEPLOYMENTS};ls ${dir}|egrep ${regex})|sort|uniq -u|xargs -I {} rm ${dir}/{} -r
}

repo_last_tag() {
	ref=`git for-each-ref refs/tags --sort=-*authordate --format='%(refname)' --count=1 | cut -d '/' -f 3`
	test $? -eq 0 || abort Failed to determine latest tag
	echo ${ref}
}

node_cluster_reload() {
	echo Triggering Node.js cluster reload...
	sudo naught deploy ${DEPLOY_ROOT}/${DEPLOY_ENV}/shared/naught.ipc
	test $? -eq 0 || abort Failed to trigger Node.js cluster reload.
}
