#!/bin/bash

################ config start ################

KEEP_DEPLOYMENTS=5
DEPLOY_ROOT=/var/www

################  config end  ################

abort() {
	echo
	echo "  $@" 1>&2
	echo
	exit 1
}

rollback_abort() {

	echo
	echo "  $@" 1>&2
	echo

	local path=${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	echo Removing ${path}
	rm -r ${path}
	exit 1
}

repo_get_branch() {
	if (( $# == 1 )); then
		# if first argument is set, use it as branch name
		branch=$1
	else
		# determine the branch that was pushed
		if ! [ -t 0 ]; then
		  read -a ref
		fi
		IFS='/' read -ra REF <<< "${ref[2]}"
		branch="${REF[2]}"

		# if executed manually and no argument is provided, fall back to master.
		if [ -z "$branch" ]; then
			branch="master"
		fi
	fi
	echo ${branch}
}

repo_clone() {
	local dest=${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	if [ -d "$dest" ]; then
		abort "$1 is already deployed, aborting".
	fi
	git clone ${PWD} ${dest}
    test $? -eq 0 || abort "Failed to clone ${PWD} into ${dest}"
}

repo_checkout_tag() {
	local dest=${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	cd ${dest}
	# git looks at $GIT_DIR first before checking $PWD, so let's fix that.
	unset GIT_DIR
	git checkout $1
    test $? -eq 0 || rollback_abort $1 "Failed to checkout $1, aborting."
}

repo_checkout_branch() {
	local dest=${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	cd ${dest}
	echo "Checking out branch branch ${2} at ${PWD}..."
	# git looks at $GIT_DIR first before checking $PWD, so let's fix that.
	unset GIT_DIR
	git checkout $2
	test $? -eq 0 || rollback_abort $1 "Failed to checkout branch ${2} at ${PWD}, aborting."
}

npm_install() {
	echo "Installing Node.js dependencies..."
	cd ${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	npm install
	test $? -eq 0 || rollback_abort $1 "Failed to run npm install. Manually fix and relaunch deployment.".
	echo "Installing Bower dependencies..."
	bower install --force-latest
	test $? -eq 0 || rollback_abort $1 "Failed to run bower install. Manually fix and relaunch deployment.".
}

grunt_build() {
	cd ${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	echo "Running build with Grunt..."
	APP_NAME=${DEPLOY_ENV} NODE_ENV=production APP_CACHEDIR=${DEPLOY_ROOT}/${DEPLOY_ENV}/shared/cache grunt build --force
	test $? -eq 0 || rollback_abort $1 "Grunt build failed. Fix and redeploy."
}

repo_link() {
	local dest=${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
	local newSettings=${DEPLOY_ROOT}/${DEPLOY_ENV}/config/${1}.js
	local currentSettings=${DEPLOY_ROOT}/${DEPLOY_ENV}/settings.js
	local patchedSettings=${DEPLOY_ROOT}/${DEPLOY_ENV}/settings-patched.js

	if [ ! -f "$newSettings" ]; then
		echo Copying settings...

		if [ -f "$patchedSettings" ]; then
			echo "Copying ${patchedSettings} instead of ${currentSettings}."
			cp ${patchedSettings} ${newSettings}
			test $? -eq 0 || rollback_abort $1 "Unable to copy settings from ${patchedSettings} to ${newSettings}. Please fix and manually relaunch deployment."
		else
			cp ${currentSettings} ${newSettings}
			test $? -eq 0 || rollback_abort $1 "Unable to copy settings from ${currentSettings} to ${newSettings}. Please fix and manually relaunch deployment."
		fi
	else
		echo "Settings file already found at ${newSettings}"
	fi
	ln -sfn ${newSettings} ${patchedSettings}


	echo Migrating settings...
	APP_SETTINGS=${newSettings} node ${dest}/server/config/migrate.js
	test $? -eq 0 || rollback_abort $1 "New @important config settings. Please fix settings at ${patchedSettings} and manually finish deployment."

	echo Validating settings...
	APP_SETTINGS=${newSettings} node ${dest}/server/config/validate.js
	test $? -eq 0 || rollback_abort $1 "Setting validation failed. Please fix settings at ${patchedSettings} and manually finish deployment."

	echo Swapping settings...
	ln -sfn ${newSettings} ${currentSettings}
	test $? -eq 0 || rollback_abort $1 "Error linking new settings. Please fix and manually finish deployment."
	rm ${patchedSettings}

	echo Swapping code...
	ln -sfn ${dest} ${DEPLOY_ROOT}/${DEPLOY_ENV}/current
	test $? -eq 0 || rollback_abort $1 "Failed to symlink current repo."
}

repo_cleanup() {
	local regex=$1
	local dir=${DEPLOY_ROOT}/${DEPLOY_ENV}
	echo Deleting old deployments:
	(ls -t ${dir}|egrep ${regex}|head -n ${KEEP_DEPLOYMENTS};ls ${dir}|egrep ${regex})|sort|uniq -u|xargs -I {} echo "   * ${dir}/{}"
	(ls -t ${dir}|egrep ${regex}|head -n ${KEEP_DEPLOYMENTS};ls ${dir}|egrep ${regex})|sort|uniq -u|xargs -I {} rm ${dir}/{} -r
}

repo_last_tag() {
	ref=`git for-each-ref refs/tags --sort=-*authordate --format='%(refname)' --count=1 | cut -d '/' -f 3`
	test $? -eq 0 || abort "Failed to determine latest tag"
	echo ${ref}
}

node_cluster_reload() {
	echo Deploying new code...
	naught deploy ${DEPLOY_ROOT}/${DEPLOY_ENV}/shared/naught.ipc
	test $? -eq 0 || abort "Failed to trigger Node.js cluster reload."
}
