#!/bin/bash

DEPLOY_ENV='staging'

. ./hooks/common

BRANCH=`repo_get_branch $1`
HEAD_REV=`git rev-parse ${BRANCH}`
HEAD_REV=${HEAD_REV:0:10}

DIRNAME=${BRANCH}-${HEAD_REV}

# 1. clone into new folder
repo_clone ${DIRNAME}
repo_checkout_branch ${DIRNAME} ${BRANCH}

# 2. install node packages and build
npm_install ${DIRNAME}
grunt_build ${DIRNAME}

# 3. change symlink
repo_link ${DIRNAME}

# 4. reload node cluster
node_cluster_reload

# 5. cleanup old deployment
repo_cleanup "[a-z0-9_\\\\-]-[a-f0-9]{10}"

echo ==================================================================
echo Staging deployment successful!
echo ==================================================================
