#!/bin/bash

DEPLOY_ENV='production'
ROLLBACK=0

# Re-launch as deployer if root
if [ "$(id -u)" == "0" ]; then
	sudo -i -H  -u deployer SPWD="$PWD" SCRIPT="$0" BRANCH="$1" COMMIT="$2" bash -c 'cd $SPWD; "$SCRIPT" $BRANCH $COMMIT'
	exit $?
fi

. ./hooks/common

LAST_TAG=`repo_last_tag`
if [ -z "$LAST_TAG" ]; then
	abort No tag found.
fi

echo Deploying version ${LAST_TAG}...

# 1. clone into new folder
repo_clone ${LAST_TAG}
repo_checkout_tag ${LAST_TAG}

# 2. install node packages
npm_install ${LAST_TAG}

# 3. compile to javascript
build ${LAST_TAG}

# 4. change symlink
repo_link ${LAST_TAG}

# 5. reload node cluster
node_cluster_reload

# 6. post scripts
post_scripts ${LAST_TAG}

# 7. cleanup old deployment
repo_cleanup "v[0-9]+\.[0-9]+\.[0-9]+"

echo ==================================================================
echo Production deployment successful!
echo ==================================================================
