displayName: Backglasses
description: |
  Backglasses are the interactive images of the translite while playing
  a table.

  Currently the only supported format is DirectB2S. Every backglass is linked
  to the game by having the same file name as the table file.

  Note that the `_game` attribute is optional, but only if the linked file
  contains a reference to a ROM and that ROM already exists in the database.

post:
  is: [ validated ]
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    Create a new backglass.

  body:
    role/member:
      schema: build
      example: !include http/create-req.json
  responses:
    201:
      body:
        role/member:
          schema: build
          example: !include http/create-res-201.json
    422:
      body:
        role/member:
          example: !include http/create-res-422.json
