displayName: Tokens
description: |
  Access Tokens function like ordinary JWT access tokens. They can be used
  instead of a password for full API access. They are useful if you need
  a third party application such as PinballX to authenticate without giving
  it your password.

post:
  is: [ validated ]
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    Create a new access token.

    Due to the sensibility of this request, the user's password must be
    provided.

    Additionally, the response of this request is the only way to retrieve the
    actual token, listing will only return the meta data.

  body:
    role/member:
      example: !include http/create-req.json
  responses:
    201:
      body:
        role/member:
          example: !include http/create-res-201.json
    401:
      body:
        role/member:
          example: !include http/create-res-401.json

get:
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    List all access tokens.

    Note there is no actual token returned. If a token was not copied and saved
    after creation, it can be deleted and must be re-created.

  body:
    role/member:
      example: !include http/list-req.json
  responses:
    200:
      body:
        role/member:
          example: !include http/list-res-200.json

/{token_id}:
  delete:
      is: [ protected ]
      securedBy: [ jwt: { scopes: [ MEMBER ] } ]
      description: |
        Delete an access token of a given ID.

        As soon as the token is deleted, any third party applications that are
        still configured with it, won't get authenticated anymore.

      body:
        role/member:
          example: !include http/del-req.json
      responses:
        204:
          body:
            role/member:
              example: !include http/del-res-204.json