displayName: Tokens
description: |
  Application access tokens function like ordinary JWT access tokens. They can
  be used in the header for full API access. Their goal is to give third party
  applications access to the API without having to hand them your password.

post:
  is: [ validated ]
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    Create a new application access token.

    Due to the sensibility of this request, the user's password must be
    provided.

    Additionally, the response of this request is the only way to retrieve the
    actual token, listing will only return the meta data.

  body:
    role/member:
      example: !include http/create-req.json
  responses:
    201:
      body:
        role/member:
          example: !include http/create-res-201.json
    401:
      description: Password not provided.
      body:
        role/member:
          example: !include http/create-res-401.json

get:
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    List all application access tokens.

    Note there is no actual token returned. If a token was not copied and saved
    after creation, it can be deleted and must be re-created.

  body:
    role/member:
      example: !include http/list-req.json
  responses:
    200:
      body:
        role/member:
          example: !include http/list-res-200.json

/{token_id}:
  patch:
    is: [ protected ]
    securedBy: [ jwt: { scopes: [ MEMBER ] } ]
    description: |
      Updates any number of fields of a token.

      Allowed fields are `label`, `is_active` and `expires_at`.

    body:
      role/member:
        example: !include http/patch-req.json
    responses:
      200:
        body:
          role/member:
            example: !include http/patch-res-200.json
      422:
        body:
          role/member:
            example: !include http/patch-res-422.json

  delete:
    is: [ protected ]
    securedBy: [ jwt: { scopes: [ MEMBER ] } ]
    description: |
      Delete an application access token of a given ID.

      As soon as the token is deleted, any third party applications that are
      still configured with it, won't get authenticated anymore.

    body:
      role/member:
        example: !include http/del-req.json
    responses:
      204:
        body:
          role/member:
            example: !include http/del-res-204.json
