displayName: VP Builds
description: |
  When submitting table files for a [release][release], every file must
  reference at least one compatible build of Visual Pinball.

  A VP build can be an official release, a daily build or an experimental test
  build.

  Note that this resource doesn't contain the actual build but acts as a
  marker, similar to [tags][tag]. The primary goal is to inform the user about
  the VP table's compatibility as well as easily filtering releases that
  contain table files for a given build.

  [release]: api://core/releases
  [tag]: api://core/tags

post:
  is: [ validated ]
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    Create a new VP build.

  body:
    role/member:
      schema: vpbuild
      example: !include http/create-req.json
  responses:
    201:
      body:
        role/member:
          schema: vpbuild
          example: !include http/create-res-201.json
    422:
      body:
        role/member:
          example: !include http/create-res-422.json

get:
  securedBy: [ ]
  description: |
    List VP builds.

    Note that this resource isn't paginated, there should only a few dozen
    of VP builds for some time.
  body:
    role/anon:
      example: !include http/list-req.json
  responses:
    200:
      body:
        role/anon:
          example: !include http/list-res-200.json

/{vpbuild_id}:
  delete:
    is: [ protected ]
    securedBy: [ jwt: { scopes: [ MEMBER, CONTRIB ] } ]
    description: |
      Delete a VP build of a given ID.

      Members can only delete own VP builds, while contributors can delete any VP build.
    responses:
      401:
        body:
          role/anon:
            example: !include http/del-res-401.json
      403:
        body:
          role/member:
            example: !include http/del-res-403.json