displayName: Releases
description: !include releases.md
post:
  is: [ validated ]
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    Create a new release.

    Note that prior to that request, files and media need to be uploaded so it
    can be referenced.
  body:
    role/member:
      schema: release
      example: !include http/create-req.json
  responses:
    201:
      body:
        role/member:
          schema: release
          example: !include http/create-res-201.json

/{release_id}:
  uriParameters:
   release_id:
     displayName: Release ID
     type: string
  delete:
    is: [ protected ]
    securedBy: [ jwt: { scopes: [ CONTRIBUTOR ] } ]
    description: |
      Delete a release of a given ID.

      Note that deleting releases is only possible in the first 24 hours after
      creation.
    responses:
      401:
        body:
           role/anon:
            example: !include http/del-res-401.json

  /comments:
    post:
      is: [ validated ]
      securedBy: [ jwt: { scopes: [ MEMBER ] } ]
      description: |
        Add a commentary to a release.
      body:
        role/member:
          schema: comment
          example: !include http/create-comment-req.json
      responses:
        201:
          body:
            role/member:
              schema: comment
              example: !include http/create-comment-res-201.json
    get:
      description: List all comments of a release.