displayName: Releases
description: !include releases.md
post:
  is: [ validated ]
  securedBy: [ jwt: { scopes: [ MEMBER ] } ]
  description: |
    Create a new release.

    Note that prior to that request, files and media need to be uploaded so it
    can be referenced.
  body:
    role/member:
      schema: release
      example: !include http/create-req.json
  responses:
    201:
      body:
        role/member:
          schema: release
          example: !include http/create-res-201.json
get:
  securedBy: [ ]
  is: [ paginated: { defaultPerPage: 12, maxPerPage: 60 } ]
  description: |
    List all releases.

/{release_id}:
  uriParameters:
    release_id:
      displayName: Release ID
      type: string

  get:
    securedBy: [ ]
    description: |
      List details of a given release.
    body:
        role/anon:
          example: !include http/view-req.json
    responses:
      200:
        body:
          role/member:
            example: !include http/view-res-200.json

  delete:
    is: [ protected ]
    securedBy: [ jwt: { scopes: [ CONTRIBUTOR ] } ]
    description: |
      Delete a release of a given ID.

      Note that deleting releases is only possible in the first 24 hours after
      creation.
    responses:
      401:
        body:
          role/anon:
            example: !include http/del-res-401.json

  /versions:
    post:
      is: [ validated ]
      securedBy: [ jwt: { scopes: [ MEMBER ] } ]
      description: |
        Add a new version to an existing release.

        Note that prior to that request, files and media need to be uploaded so it
        can be referenced.
      body:
        role/member:
          example: !include http/create-version-req.json
      responses:
        201:
          body:
            role/member:
              example: !include http/create-version-res-201.json
        422:
          body:
            role/member:
              example: !include http/create-version-res-422.json
        403:
          description: A user who is not author of the release posted a new version
          body:
            role/member:
              example: !include http/create-version-res-403.json

    /{version}:
      uriParameters:
        version:
          displayName: Version ID
          type: string
      put:
        is: [ validated ]
        securedBy: [ jwt: { scopes: [ MEMBER ] } ]
        description: |
          Update an existing version of a release.

          Provided files wil be *added* to the version. It's not possible to
          delete files. It's also the only field looked at at the moment.

          Note that prior to that request, files and media need to be uploaded so it
          can be referenced.
        body:
          role/member:
            example: !include http/update-version-req.json
        responses:
          201:
            body:
              role/member:
                example: !include http/update-version-res-201.json
          422:
            body:
              role/member:
                example: !include http/update-version-res-422.json
          403:
            description: A user who is not author of the release posted a new file
            body:
              role/member:
                example: !include http/update-version-res-403.json

  /comments: !include comments.raml
  /rating: !include rating.raml
  /star: !include star.raml
